### ISSUE TITLE
Support for PHP 7.3.9

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-I18N#10]
Just for info with php 7.3.9 show this error.

```
Error: Class 'Locale' not found in file Z:\ws\www\foundation\vendor\delight-im\i18n\src\Locale.php on line 141
Stack trace:
  1. Error->() Z:\ws\www\foundation\vendor\delight-im\i18n\src\Locale.php:141
  2. Delight\I18n\Locale->toLanguageCode() Z:\ws\www\foundation\vendor\delight-im\i18n\src\Http.php:38
  3. Delight\I18n\Http->matchClientLanguages() Z:\ws\www\foundation\vendor\delight-im\i18n\src\I18n.php:115
  4. Delight\I18n\I18n->setLocaleAutomatically() Z:\ws\www\foundation\vendor\delight-im\foundation-core\src\App.php:116
  5. Delight\Foundation\App->__construct() Z:\ws\www\foundation\index.php:80
```

**Comment by ocram** [comment]
Thanks!

Are you sure it’s not just that you don’t have the `intl` extension installed with PHP 7.3?

**Comment by daebak74** [comment]
intl is installed for both if I switch in 7.1.32 work but on 7.3.9 give me that message. I am using 7.1.32 so I don't care. I noticed to you just for let you check.

**Comment by ocram** [comment]
Can you check if it’s actually *enabled* as well for PHP 7.3? Perhaps using `phpinfo()`, `$ php -i` or `$ php -m`?

**Comment by daebak74** [comment]
You are right in 7.3.9 in phpinfo is not present. From Wamp Server is enabled and don't give me any error but if I check with phpinfo doesn't show enabled. I don't know why.

**Comment by ocram** [comment]
On some platforms, in addition to installing the extension, you have to uncomment `extension=php_intl.dll` in `php.ini` or move around some DLLs.
