### ISSUE TITLE
Library not returning (any) translated text(s)

### ISSUE THREAD

**Issue by FALL1N1** [delight-im/PHP-I18N#14]
Hello,

First, thank you for the amazing library and the hours spent on it also I am sorry for posting here as this is not an actual issue, most likely something that I am not doing as intended.

In short, I have followed the steps several times, removed and re-installed the lib several times, however nothing seems to be as expected.

The issue is that upon creating the translations, rebuilding the files so they can get a fresh .mo file with the text, the string on the PHP side still remains the variable name and not the actual translation. I have restarted the Apache several times just in case the .mo files were cached, although it did not help.

Can someone throw some enlightenment whether I am missing something? There are no php errors whatsoever :(

Server specs:

> CentOS7.9
> PHP 8.2
> Apache/2.4.58 (cPanel)
> 
> [root@homelab testlolz]# ea-php82 -m |grep int
> intl
> 
> [root@homelab testlolz]# ea-php82 -m |grep gett
> gettext

My code:

```
require 'vendor/autoload.php';
 
$i18n = new \Delight\I18n\I18n([
    \Delight\I18n\Codes::EN_US,
    \Delight\I18n\Codes::BG_BG, 
    \Delight\I18n\Codes::RU_RU, 
]);

$i18n->setLocaleManually('bg-BG');
echo _('home.hello'); 

echo "<br>"; 

echo $i18n->getLocaleName();
```

Output:
```
home.hello

български (България) 
```

The .po file content:

```
#
msgid ""
msgstr ""
"Language: bg-BG\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "home.hello"
msgstr "здравей" 
```

The file structure is by default:

> /home/testlolz/public_html/locale/bg-BG/LC_MESSAGES

**Comment by FALL1N1** [comment]
The issue was that on CentOS the locales were with an underscore rather than a hyphen, e.g:

en_US

than

en-US

If someone is experiencing such issue, run this via shell (SSH) terminal:

```
[root@homelab testlolz]$ locale -a|grep BG
bg_BG
bg_BG.cp1251
bg_BG.utf8
```


for the locale you want to use

**Comment by ocram** [comment]
Thanks a lot for your perfect report!

And no problem, since you reported your solution, this can be useful to others as well.

So what you did in the end was change the directory names from underscore to hyphen since you found the output of `locale -a` is using underscore as well?

By the way, the general best practice is to use the actual default translations (often English) and not any keys or placeholders. So you would not be using `_('home.hello')` but simply `_('Hello!')` or something. If you want to provide context, which the `home.` prefix implies, there is an option to provide context. But of course you can ignore this advice and still use keys or placeholders, it will still work.

**Comment by FALL1N1** [comment]
Yes, that was the issue, since I am used to work with debian-based distros I was used to having the locales with hyphens rather than underscores, although that's CentOS (RHEL-based) and it had it's locales with underscores, e.g "en_US" rather than "en-US".

What I did was just to generate them accordingly:

```
./i18n.sh bg_BG "" "" nofuzzy
./i18n.sh en_US "" "" nofuzzy
./i18n.sh ru_RU "" "" nofuzzy
```

added some random text in the 'msgstr' line and it worked out like a charm.


Seems to be like that with all RHEL-based ones (CentOS, Alma, Rocky), just tested them all (I work in a hosting company so we have all distros here at our disposal).

As of the practice, thank you, that's exactly my plan, I just slapped something in order to test it.. I am still planning out how would be the best way to handle the localization, because there will be a lot of content within the database, so I might just create several tables for locales and cache them in redis/memcached, but that's a completely different story, unrelated to the topic here.

**Comment by ocram** [comment]
Thanks for your explanation!

I’ve added two explanations to the README now which should address the hyphen/underscore issue and remind everyone to make sure they use the right syntax:

https://github.com/delight-im/PHP-I18N/commit/398323c5fa1372dfae0b4113dc6861d20f3bdd06

That should probably help avoid issues for others in the future.

As for translatable strings in the database, that is a very common challenge, but unfortunately not totally easy to solve, especially with tooling. The thing is, translating the strings from the database works fine, you can just pass them from the database to the helper methods for translating from this library.

But detecting and extracting them in your project with the available tools is not always easy. You may try dumping them all from your database to an unused script file only used for the very purpose of extracting them, wrapping the database output in translation helper calls.
