### ISSUE TITLE
Add PHPUnit for unit test

### ISSUE THREAD

**Issue by peter279k** [delight-im/PHP-I18N#5]
As title, I think we can add the unit test with PHPUnit in `tests` folder.

If possible, I glad I can help this issue :).

**Comment by ocram** [comment]
Thanks!

As you may have seen, we already have some tests in the `tests/` directory, which cover most of the functionality in this library. Though these are obviously written without PHPUnit.

Is there anything specific missing in your opinion, or are there any particular advantages you hope for when using PHPUnit instead?

**Comment by peter279k** [comment]
@ocram, I hope I can use the PPHUnit instead to complete unit tests if possible.

**Comment by ocram** [comment]
The tests should already be pretty much complete.

We appreciate your help, but we’re not sure whether we want to switch to PHPUnit just for the sake of making the switch, without any specific advantages that we want to achieve.

**Comment by peter279k** [comment]
Hi @ocram, thank you for your reply.

I think using the unit tests has the following advantages:

- Organize the all tests for the source code.
- We can use the coverage tool to evaluate the code covers and we can also refer the coverage report.
- Using the assertions to make developers clearly know the package usage and actual test behaviors.

**Comment by ocram** [comment]
Thanks, we’ll consider this again in the future for the coverage information and for doing it the standard way, but for now, we don’t want to switch to PHPUnit here.
