### ISSUE TITLE
PHPUnit tests are sorely needed

### ISSUE THREAD

**Issue by hopeseekr** [delight-im/PHP-I18N#7]
Very few people are going to trust this if it doesn't have a single PHPUnit test.

Ideally, it needs 100% code coverage with every happy and sad path tested. See 
* https://github.com/phpexpertsinc/SimpleDTO#use-cases
* https://github.com/phpexpertsinc/RESTSpeaker#use-cases

**Comment by ocram** [comment]
Thanks!

There *are* tests, of course, in `tests/index.php`, but they do not use PHPUnit. This shouldn’t change their validity or lack thereof, but we’re open to having PHPUnit tests (as well).

This might even be a good starting point for contributors.

**Comment by ocram** [comment]
We do not really care if an approach is “old school” or modern.

All we care about is whether it’s doing its job and is simple to read and maintain, which the current tests are.

Thus, given other priorities and more urgent problems, we won’t change anything for now.

Thanks nevertheless!
